fix: algolia search flicker
elasticpath/d2c-starter-kit pull request #63
Opened 2022-11-17 10:52 UTC by butikden

2022-11-18 17:54 UTC, field123 requested changes

2022-11-18 17:54 UTC, field123 commented on src/lib/search-props.tsx
> +    console.warn(node, "node");
Do we want this log?

2022-11-21 09:38 UTC, butikden commented on src/lib/search-props.tsx
> +    console.warn(node, "node");
no, deleted it.

2022-11-21 11:04 UTC, field123 approved these changes

2022-11-21 11:15 UTC, merged